# Generated by Django 5.2.3 on 2025-06-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="tittle",
            new_name="title",
        ),
    ]
